//
//  LLMR2UploadProvider.swift
//  LLMKit
//
//  Created by Chocoford on 10/5/25.
//

import Foundation
import CryptoKit
import Logging
import LLMCore

private struct R2PresignUploadRequest: Codable {
    var fileName: String
    var mimeType: String
    var bodyHash: String
    var contentLength: Int
}

private struct R2PresignUploadResponse: Codable {
    var uploadURL: URL
    var publicURL: URL
    var objectKey: String
    var headers: [String: String]
}

public protocol LLMFileUploadProviderBuilder: Sendable {
    func callAsFunction(_ networking: LLMNetworking) -> LLMFileUploadProvider
}

public struct LLMR2UploadProviderBuilder: LLMFileUploadProviderBuilder {
    var endpoint: URL
    var bucket: String
    
    public func callAsFunction(_ networking: LLMNetworking) -> any LLMFileUploadProvider {
        LLMR2UploadProvider(
            endpoint: endpoint,
            bucket: bucket,
            networking: networking
        )
    }
    
}

extension LLMFileUploadProviderBuilder where Self == LLMR2UploadProviderBuilder {
    @available(*, deprecated, message: "R2 upload target is now generated by LLMServer via /upload/r2-presign; custom endpoint/bucket are ignored by the server-side presign flow.")
    public static var `default`: LLMR2UploadProviderBuilder {
        Self.r2(
            endpoint: URL(string: "https://3d471aa1d195619b5b45f0009f0b72f9.r2.cloudflarestorage.com")!,
            bucket: "choco-llm"
        )
    }
    
    @available(*, deprecated, message: "R2 upload target is now generated by LLMServer via /upload/r2-presign; custom endpoint/bucket are ignored by the server-side presign flow.")
    public static func r2(
        endpoint: URL,
        bucket: String,
    ) -> LLMR2UploadProviderBuilder {
        LLMR2UploadProviderBuilder(endpoint: endpoint, bucket: bucket)
    }
}

public struct LLMR2UploadProvider: LLMFileUploadProvider {
    private let logger = Logger(label: "LLMR2UploadProvider")
    
    var endpoint: URL
    var bucket: String
    var networking: LLMNetworking

    public init(endpoint: URL, bucket: String, networking: LLMNetworking) {
        self.endpoint = endpoint
        self.bucket = bucket
        self.networking = networking
    }

    public func uploadFile(
        data: Data,
        fileName: String,
        mimeType: String
    ) async throws -> URL {
        // 1️⃣ 计算 SHA256
        let sha256 = SHA256.hash(data: data)
        let sha256Hex = sha256.map { String(format: "%02x", $0) }.joined()

        let presign: R2PresignUploadResponse = try await self.networking.post(
            "/upload/r2-presign",
            body: R2PresignUploadRequest(
                fileName: fileName,
                mimeType: mimeType,
                bodyHash: sha256Hex,
                contentLength: data.count
            )
        )

        logger.info("Uploading file to \(presign.uploadURL.absoluteString)")

        var request = URLRequest(url: presign.uploadURL)
        request.httpMethod = "PUT"
        request.httpBody = data
        for (key, value) in presign.headers {
            request.setValue(value, forHTTPHeaderField: key)
        }
        
        // Perform request
        let (responseData, response) = try await URLSession.shared.data(for: request)
        
        guard let http = response as? HTTPURLResponse else {
            throw NSError(domain: "LLMUpload", code: -1, userInfo: [
                NSLocalizedDescriptionKey: "Invalid response type"
            ])
        }
        
        guard (200..<300).contains(http.statusCode) else {
            // Try to decode AWS-style XML error
            let xml = String(data: responseData, encoding: .utf8) ?? "(empty)"
            var message = "Upload failed (\(http.statusCode))"
            
            if let code = xml.capture(between: "<Code>", and: "</Code>"),
               let msg = xml.capture(between: "<Message>", and: "</Message>") {
                message += " — \(code): \(msg)"
            }
            
            // 🪵 Log the full context
            logger.error(
                """
                ❌ Upload failed
                URL: \(presign.uploadURL.absoluteString)
                Status: \(http.statusCode)
                Response: \(xml)
                """
            )
            
            throw NSError(domain: "LLMUpload", code: http.statusCode, userInfo: [
                NSLocalizedDescriptionKey: message
            ])
        }
        
        logger.info("✅ Upload successful: \(presign.uploadURL.absoluteString)")
        
        return presign.publicURL
    }
}


// 小工具函数（轻量解析 XML）
private extension String {
    func capture(between start: String, and end: String) -> String? {
        guard let r1 = range(of: start),
              let r2 = range(of: end, range: r1.upperBound..<endIndex)
        else { return nil }
        return String(self[r1.upperBound..<r2.lowerBound])
    }
}
